import { z } from 'zod';

export const donationSchema = z.object({
  body: z.object({
    donorName: z.string().min(2, 'Donor name must be at least 2 characters'),
    mobile: z.string().optional(),
    phone: z.string().optional(),
    email: z.string().email('Invalid email').optional().or(z.literal('')),
    address: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    pincode: z.string().optional(),
    panNumber: z.string().optional(),
    aadhaarNumber: z.string().optional(),
    existingDonor: z.boolean().optional(),
    memberType: z.enum(['Member', 'Non-member']).optional(),
    donationType: z.string().min(1, 'Donation type is required'),
    type: z.string().optional(),
    category: z.string().optional(),
    amount: z.number().nonnegative('Amount cannot be negative'),
    itemDescription: z.string().optional(),
    itemDetails: z.string().optional(),
    purpose: z.string().optional(),
    paymentMethod: z.string().optional(),
    paymentStatus: z.enum(['Paid', 'Due', 'Partial']).optional(),
    paidAmount: z.number().nonnegative('Paid amount cannot be negative').optional(),
    dueAmount: z.number().nonnegative('Due amount cannot be negative').optional(),
    upiReferenceNumber: z.string().optional(),
    transactionId: z.string().optional(),
    transactionReference: z.string().optional(),
    bankName: z.string().optional(),
    chequeNumber: z.string().optional(),
    remarks: z.string().optional(),
    notes: z.string().optional(),
    isPublic: z.boolean().optional(),
    status: z.enum(['Pending', 'Verified', 'Cancelled']).optional(),
    date: z.string().datetime().optional().or(z.string()).or(z.date()).optional(),
    donationDate: z.string().datetime().optional().or(z.string()).or(z.date()).optional(),
    receiptNumber: z.string().optional(),
  }),
});
